import { getHeroImages, getImages } from "./data";
import type { ImageRecord } from "./types";
import reel from "@/data/reel.json";

// The homepage reel uses a brightness-measured, hand-curated set (data/reel.json,
// generated by scoring web/ derivatives) so the full-bleed hero is never a dark
// night frame. Falls back to the heuristic below if the list is empty.
export function reelImages(n = 10): ImageRecord[] {
  const paths = reel as string[];
  if (paths.length) {
    const byPath = new Map(getImages().map((i) => [i.path, i]));
    const picked = paths.map((p) => byPath.get(p)).filter((x): x is ImageRecord => !!x);
    if (picked.length) return picked.slice(0, n);
  }
  return reelHeuristic(n);
}

function reelHeuristic(n = 10): ImageRecord[] {
  const wide = getHeroImages().filter(
    (i) => i.width && i.height && i.width / i.height > 1.3,
  );
  // Full-bleed heroes need BRIGHT, well-exposed frames. Night-fire shots are mostly
  // black full-screen (they shine as small gallery tiles, not as a hero), so we
  // favour daylight/dusk sculptures, sunsets, and crew-in-light.
  const score = (i: ImageRecord) => {
    const s0 = i.subject.toLowerCase();
    let s = 0;
    if (i.tags.includes("bm-gallery")) s += 6; // pro shots, often bright skies/sunsets
    if (i.tags.includes("flickr")) s += 3;
    if (i.file.includes("dngprev")) s -= 4;
    if (i.tags.includes("burn-night")) s -= 5; // too dark full-bleed
    if (/(sunrise|sunset|dawn|dusk|day|playa|sky|moon|silhouet)/.test(s0)) s += 3;
    if (/(charlie|crew|crowd|portrait|build)/.test(s0)) s += 2;
    if (["fire-birds", "hearth", "fleeble-flobbler", "infinite-infant", "red-hot-cock", "time-star"].includes(i.work_id ?? "")) s += 2;
    if ((i.long_edge ?? 0) >= 3000) s += 1;
    return s;
  };
  // de-dupe by work so the reel isn't 8 Red Hot Cock frames in a row
  const sorted = [...wide].sort((a, b) => score(b) - score(a));
  const picked: ImageRecord[] = [];
  const perWork = new Map<string, number>();
  for (const img of sorted) {
    const k = img.work_id ?? img.file;
    const c = perWork.get(k) ?? 0;
    if (c >= 2) continue;
    perWork.set(k, c + 1);
    picked.push(img);
    if (picked.length >= n) break;
  }
  return picked;
}
