// Images are served from the public archive repo on GitHub.
// - displayUrl: a 1600px JPEG derivative (web/<path>.jpg) — small + fast, used in grids.
// - imageUrl:   the full-resolution original — used for the lightbox "full-res" link.
// Derivatives are generated by scripts/build-derivatives.mjs.

const RAW_BASE =
  "https://raw.githubusercontent.com/WalksWithASwagger/uncle-charlie-smith/main";

function enc(path: string): string {
  return path
    .split("/")
    .map((seg) => encodeURIComponent(seg))
    .join("/");
}

/** Full-resolution original URL for an archive image `path`. */
export function imageUrl(path: string): string {
  return `${RAW_BASE}/${enc(path)}`;
}

/** 1600px display derivative (web/<path>.jpg). Falls back to the original if absent. */
export function displayUrl(path: string): string {
  return `${RAW_BASE}/web/${enc(path)}.jpg`;
}

/** Warm ember-tinted blur placeholder so loading tiles read as "warming up", not dead-black. */
export const BLUR =
  "data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='6'%3E%3Crect width='8' height='6' fill='%23211711'/%3E%3Cellipse cx='4' cy='6' rx='5' ry='3' fill='%234a2a18'/%3E%3C/svg%3E";

